
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/components/auth-provider";
import { BookingProvider } from "@/components/bookingContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthContextProvider>
          <BookingProvider>
            {children}
          </BookingProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}